---
# autofs_service:
#   install: true
#   enable: true

# autofs_mount_points:
#   - data
#   - jwd
#   - usrlocal

# autofs_conf_files:
#   data:
#     - galaxy_data      -rw,hard,nosuid      192.52.43.233:/nfs_shares/&
#   jwd:
#     - jwd01            -rw,hard,nosuid      192.52.43.233:/nfs_shares/&
#   usrlocal:
#     - /usr/local/tools   -rw,hard,nosuid     192.52.43.233:/nfs_shares/tools
