---
# Role: usegalaxy_eu.handy.os_setup
enable_hostname: true
enable_powertools: true
enable_remap_user: true
enable_exclude_packages: true
enable_pam_limits: true
enable_install_software: true
enable_create_user: true
software_groups_to_install:
  - admin
  - debug
  - editors
  - terminals
  - utils
handy_users:
  - user_name: "{{ galaxy_user.name }}"
    user_uid: "{{ galaxy_user.uid }}"
    user_group: "{{ galaxy_group.name }}"
    user_comment: "Galaxy useraccount"
    user_create_home: "{{ galaxy_user.create_home }}"
    user_home: "{{ galaxy_user.home }}"
    user_shell: "{{ galaxy_user.shell }}"
handy_groups:
  - group_name: "{{ galaxy_group.name }}"
    group_gid: "{{ galaxy_group.gid }}"

# Role: autofs
autofs_service:
  install: true
  enable: true
autofs_mount_points:
  - data
  - jwd
  - usrlocal
autofs_conf_files:
  data:
    - galaxy_data      -rw,hard,nosuid      192.52.43.77:/nfs_shares/&
  jwd:
    - jwd01            -rw,hard,nosuid      192.52.43.77:/nfs_shares/&
  usrlocal:
    - /usr/local/tools   -rw,hard,nosuid     192.52.43.77:/nfs_shares/tools
    - /opt/galaxy        -rw,hard,nosuid     192.52.43.77:/nfs_shares/galaxy_main
