---
user_name: galaxy
user_group_name: galaxy

# create_user task
handy_groups:
  - group_name: "{{ user_group_name }}"
    group_gid: 999

handy_users:
  - user_name: "{{ user_name }}"
    user_uid: 999
    user_comment: rustus Service-Acct
    user_group: "{{ user_group_name }}"

# Autofs
autofs_service:
  install: true
  enable: true
nfs_kernel_tuning: true

autofs_mount_points:
  - data
  - gxtest
  - gxkey
  - jwd

# usegalaxy_eu.handy.os_setup
## packages
software_groups_to_install:
  - editors
  - utils

## kernel_5
kernel_5_package: kernel-ml