---
- name: Install packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - autofs
    - nfs-utils

- name: Enable and start autofs
  systemd:
    name: autofs
    state: started
    enabled: true
