---
# NOTE: Use dashes (-) exclusively for tags and underscores (_) exclusively for destinations.
# submit_request_cpus its called in pulsar and in plain condor only request_cpus
destinations:
  ######################
  # BASIC DESTINATIONS #
  ######################
  basic_docker_destination:
    abstract: true
    params:
      docker_enabled: true
      docker_sudo: false
      docker_net: bridge
      docker_auto_rm: true
      docker_set_user: ''
      # $defaults expands to "$galaxy_root:ro,$tool_directory:ro,$job_directory:ro,$working_directory:rw,$default_file_path:rw"
      docker_volumes: '$_CONDOR_SCRATCH_DIR:rw,
        $defaults,
        /cvmfs/data.galaxyproject.org:ro'
      require_container: true
      submit_request_cpus: '{cores}'
      submit_request_memory: '{mem}G'
      outputs_to_working_directory: false
      container_monitor_result: callback

  basic_singularity_destination:
    abstract: true
    params:
      submit_request_cpus: '{cores}'
      submit_request_memory: '{mem}G'
      singularity_enabled: true
      singularity_volumes: '$_CONDOR_SCRATCH_DIR:rw,
        $job_directory:rw,
        $tool_directory:ro,
        $job_directory/outputs:rw,
        $working_directory:rw'
      singularity_default_container_id: '/cvmfs/singularity.galaxyproject.org/all/centos:8.3.2011'

  #############################
  # LOCAL CONDOR DESTINATIONS #
  #############################

  condor_docker:
    inherits: basic_docker_destination
    runner: condor
    max_accepted_cores: 16
    max_accepted_mem: 32
    min_accepted_gpus: 0
    max_accepted_gpus: 0
    scheduling:
      require:
        - docker

  condor_singularity:
    inherits: basic_singularity_destination
    runner: condor
    max_accepted_cores: 16
    max_accepted_mem: 32
    min_accepted_gpus: 0
    max_accepted_gpus: 0
    params:
    scheduling:
      require:
        - singularity

  # Generic destination for tools that don't get any params
  # and no specified dependency resolution
  condor_tpv:
    runner: condor
    max_accepted_cores: 16
    max_accepted_mem: 32
    min_accepted_gpus: 0
    max_accepted_gpus: 0
    scheduling:
      prefer:
        - condor-tpv

  condor_singularity_with_conda:
    inherits: basic_singularity_destination
    runner: condor
    max_accepted_cores: 16
    max_accepted_mem: 32
    min_accepted_gpus: 0
    max_accepted_gpus: 0
    params:
      container_override:
        - type: singularity
          shell: '/bin/bash'
          resolve_dependencies: true
          identifier: '/cvmfs/singularity.galaxyproject.org/all/centos:8.3.2011'
    scheduling:
      require:
        - singularity
        - conda
