---
- name: Install NFS server dependencies
  dnf:
    name:
      - nfs-utils
      - nfs4-acl-tools
      - firewalld
    state: present

- name: Start and enable nfs-server and firewalld
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nfs-server
    - firewalld
