---
- name: Install packages
  import_tasks: install_nfs_dependencies.yml

- name: Configure firewalld
  import_tasks: configure_firewall.yml

- name: Configure filesystem
  import_tasks: configure_filesystem.yml

- name: Configure NFS exports
  import_tasks: configure_nfs_exports.yml
