---
autofs_service:
  install: false
  enable: false

autofs_mount_points:
  - data
  - usrlocal

#Autofs mount points configuration files
autofs_conf_files:
  data:
    - db      -rw,hard,nosuid      192.52.43.233:/nfs_shares/&
    - jwd01   -rw,hard,nosuid      192.52.43.233:/nfs_shares/&
  usrlocal:
    - /usr/local/tools   -rw,hard,nosuid     192.52.43.233:/nfs_shares/tools
